PLAYER_CARD_DATABASE = [
    {
    "year": 2020,
    "cardType1": "Absolute",
    "first": "Justin",
    "last": "Herbert",
    "color": "167+-green+-red+-blue+-prizm+-mosaic",
    "grade": "9",
    },
    {
    "year": 2020,
    "cardType1": "Chronicles",
    "first": "Justin",
    "last": "Herbert",
    "color": "\"Prizm\"+\"Black\"+-green+-red+-mosaic+-concourse+-orange",
    "grade": "10",
    },
    {
    "year": 2020,
    "cardType1": "Prizm",
    "first": "Jalen",
    "last": "Hurts",
    "color": "343+-silver+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "10",
    },
    {
    "year": 2017,
    "cardType1": "\"Prizm\"",
    "first": "Joe",
    "last": "Mixon",
    "color": "261+silver+-black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
    {
    "year": 2017,
    "cardType1": "Prizm",
    "first": "Cooper",
    "last": "Kupp",
    "color": "203+\"silver\"+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
    {
    "year": 2019,
    "cardType1": "Prizm",
    "first": "AJ",
    "last": "Brown",
    "color": "344+-silver+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
    {
    "year": 2020,
    "cardType1": "Prizm",
    "first": "Justin",
    "last": "Jefferson",
    "color": "398+\"silver\"+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
    {
    "year": 2022,
    "cardType1": "Prizm",
    "first": "Brock",
    "last": "Purdy",
    "color": "353+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
    {
    "year": 2022,
    "cardType1": "Prizm",
    "first": "Garrett",
    "last": "Wilson",
    "color": "309+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
    {
    "year": 2017,
    "cardType1": "Prizm",
    "first": "Christian",
    "last": "McCaffrey",
    "color": "249+silver+-Black+-green+-red+-chronicles+-mosaic",
    "grade": "9",
    },
]